import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import { ScrollTop } from "@/components/ScrollToTop";

const noto = Noto_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Landressa Schiefelbein",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="pt-br"
      className={`!scroll-smooth container  ${noto.className} max-w-[1440px] mx-auto !sm:w-full !sm:mx-0 !bg-myWhite text-myBlack`}
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-P4XLT3MQ')`,
          }}
        />
      </head>
      <body>
        {/* <!-- Google Tag Manager (noscript) --> */}
        <iframe
          src="https://www.googletagmanager.com/ns.html?id=GTM-P4XLT3MQ"
          height="0"
          width="0"
        ></iframe>
        {/* <!-- End Google Tag Manager (noscript) --> */}
        {children}
        <ScrollTop />
      </body>
    </html>
  );
}
