import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import { ScrollTop } from "@/components/ScrollToTop";

const noto = Noto_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Landressa Schiefelbein",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="pt-br"
      className={`!scroll-smooth container  ${noto.className} max-w-[1440px] mx-auto !sm:w-full !sm:mx-0 !bg-myWhite text-myBlack`}
    >
      <body>
        {children}
        <ScrollTop />
      </body>
    </html>
  );
}
